INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_VERSION 1)

# set(BUILD_PREFIX "/home/rubikoid/gcc_cross/opt")
set(CMAKE_C_COMPILER "${BUILD_PREFIX}/bin/i686-elf-gcc")
set(CMAKE_ASM_COMPILER "${BUILD_PREFIX}/bin/i686-elf-gcc")
set(CMAKE_CXX_COMPILER "${BUILD_PREFIX}/bin/i686-elf-g++")

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_ASM_COMPILER_WORKS 1)

# CMAKE_FORCE_C_COMPILER(arm-elf-gcc GNU)
# CMAKE_FORCE_CXX_COMPILER(arm-elf-g++ GNU)

# CMAKE_FORCE_C_COMPILER("${BUILD_PREFIX}/bin/i686-elf-gcc" GNU)
# CMAKE_FORCE_ASM_COMPILER("${BUILD_PREFIX}/bin/i686-elf-gcc" GNU)
# CMAKE_FORCE_CXX_COMPILER("${BUILD_PREFIX}/bin/i686-elf-g++" GNU)


SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

